# docker-compose.yml

services:
  frontend:
    build: 
      context: ./frontend
      args:
        REPO_COMMIT_SHA: ${REPO_COMMIT_SHA}
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    hostname: backend
    build:
      context: ./backend
      args:
        REPO_COMMIT_SHA: ${REPO_COMMIT_SHA}
    env_file:
      - .backend.env
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - ./workspace:/workspace
    ports:
      - "3000:3000"
